## template: jinja
#cloud-config
preserve_sources_list: true
packages:
  - boundary-enterprise
write_files:
  - path: /etc/systemd/system/boundary.service
    owner: root:root
    permissions: '0755'
    content: |-
      [Unit]
      Description=Boundary Gateway
      After=network.target
      Wants=network-online.target

      [Service]
      Restart=always
      Type=simple
      ExecStart=/usr/bin/boundary server -config="/etc/boundary/gateway.hcl"

      [Install]
      WantedBy=multi-user.target
  - path: /etc/boundary/gateway.hcl
    owner: root:root
    permissions: '0644'
    content: |-
      hcp_boundary_cluster_id = "${gateway_cluster_id}"

      listener "tcp" {
        address = "0.0.0.0:9202"
        purpose = "proxy"
      }
              
      worker {
        public_addr = "${public_ip}"
        controller_generated_activation_token = "${activation_token}"
        auth_storage_path = "/etc/boundary"
        tags {
          isolation = ["dsde"]
          id = ["{{ v1.instance_id }}"]
          cloud = ["{{ v1.cloud_name }}"]
          region = ["{{ v1.region }}"]
          tags = ${tags}
        }
      }
runcmd:
  - systemctl start boundary
  - systemctl enable boundary
apt:
  sources:
    boundary:
      source: deb [arch=amd64] https://apt.releases.hashicorp.com $RELEASE main
      keyid: AA16FCBCA621E701